### ISSUE TITLE
Spurious word

### ISSUE THREAD

**Issue by PLP-Consulting** [standardebooks/fyodor-dostoevsky_poor-folk_c-j-hogarth#1]
https://github.com/standardebooks/fyodor-dostoevsky_poor-folk_c-j-hogarth/blob/07da224522f20f49bc01b08fed1c8b1559ea0a9c/src/epub/text/chapter-10.xhtml#L14

"Nevertheless, I must say that, little though you have put into your letter, that little is -not- expressed with rare beauty and grace."

The "not" is mistaken: https://archive.org/details/poorfolkgambler00dost/page/52/mode/2up

**Comment by acabal** [comment]
Thanks, this is fixed now!
