### ISSUE TITLE
More typos

### ISSUE THREAD

**Issue by PLP-Consulting** [standardebooks/fyodor-dostoevsky_poor-folk_c-j-hogarth#2]
https://github.com/standardebooks/fyodor-dostoevsky_poor-folk_c-j-hogarth/blob/24226191f4c156e143816462dcc23972ab1b1e2b/src/epub/text/chapter-38.xhtml#L14

"...and the more so as **I** recognised my fault."  ("I" missing)

https://archive.org/details/poorfolkgambler00dost/page/101/mode/1up

---
https://github.com/standardebooks/fyodor-dostoevsky_poor-folk_c-j-hogarth/blob/24226191f4c156e143816462dcc23972ab1b1e2b/src/epub/text/chapter-48.xhtml#L14

"Presently, you will **he** able to buy many..." (should be "be able")
"...and to**,** keep a carriage." (spurious comma)

https://archive.org/details/poorfolkgambler00dost/page/132/mode/1up

**Comment by acabal** [comment]
Thanks! If you're still reading please save all the typo reports for one single issue, it's much easier to manage that way.
